affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 20
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 11
symbolic.funs_name.0:
- - x
  - '0'
  - x
  - x
  - '0'
  - '0'
  - '0'
  - x
- - x^2
  - '0'
  - x
  - x
  - x
  - '0'
  - x
  - x
- - x
  - '0'
  - x
  - x
  - x
  - '0'
  - '0'
  - '0'
- - x
  - '0'
  - x
  - x
  - x
  - '0'
  - '0'
  - x
- - x
  - x
  - x
  - x
  - x
  - '0'
  - x
  - x
symbolic.funs_name.1:
- - x^2
  - x
  - x
  - x
  - x
- - x^2
  - x
  - '0'
  - x
  - x
symbolic_enabled: true
width:
- - 8
  - 0
- - 5
  - 0
- - 2
  - 0
